@startuml
agent "Patient Identifier Cross-reference Consumer" as Consumer
agent "Patient Identity Source" as Source
agent "Patient Identifier Cross-reference Manager" as Manager
Source -down-> Manager: "Patient Identity Feed FHIR [ITI-104]"
Consumer -down-> Manager : "Mobile Patient Identifier Cross-reference Query [ITI-83]"
@enduml