@startuml

agent "Patient Identifier Cross-reference Source" as Source
agent "Patient Identifier Cross-reference Consumer" as Consumer
agent "Patient Identifier Cross-reference Manager" as Manager


Source ---- Manager: "PIXm Feed [ITI-???] ↓\n PIXm Query [ITI-???] ↓\n PIXm Update [ITI-???]↓\n\n"
Consumer -- Manager : "\n\nMobile Patient Identifier Cross-reference Query [ITI-83] ↓"

@enduml
