@startuml

agent "Patient Identifier Cross-reference Source" as Source
agent "Patient Identifier Cross-reference Consumer" as Consumer
agent "Patient Identifier Cross-reference Manager" as Manager


Source --- Manager: "Mobile Patient Identifier Structure Definition [ITI-105]↓\n Mobile Patient Identifier Cross-Reference Feed [ITI-104]↓"
Consumer -- Manager : "Mobile Patient Identifier Structure Definition [ITI-105]↓\n Mobile Patient Identifier Cross-reference Query [ITI-83]↓"

@enduml
