@startuml
hide footbox
participant "Patient Identifier Cross-reference Consumer" as PatientIdentifierCrossReferenceConsumer
participant "Patient Identifier Cross-reference Manager" as PatientIdentifierCrossReferenceManager
activate "PatientIdentifierCrossReferenceConsumer"
activate "PatientIdentifierCrossReferenceManager"
"PatientIdentifierCrossReferenceConsumer" -> "PatientIdentifierCrossReferenceManager" : Get Corresponding Identifiers
"PatientIdentifierCrossReferenceManager" --> "PatientIdentifierCrossReferenceConsumer" : Response
deactivate "PatientIdentifierCrossReferenceConsumer"
deactivate "PatientIdentifierCrossReferenceManager"
@enduml
