@startuml
hide footbox

box Intensive Care domain
 participant "IC Registion \n PIXm Source" as Source1
 participant "intensive care system" as Display
endbox
participant "PIXm Manager" as Manager
box Main Hospital domain
 participant "Hospital Registration \n PIXm Source" as Source2
 participant "MHD Responder \n with lab results" as Lab
endbox

activate Source2
Source2 --> Source2: some new patient is registered
Source2 -> Manager: [01] PIXm Feed (Add) [ITI-104]
activate Manager
deactivate Source2

Manager --> Manager: [02] Apply Xref logic

activate Source1
Source1 --> Source1: patient is registered in IC
Source1 -> Manager: [03] PIXm Feed (Add) [ITI-104]
deactivate Source1

Manager -> Manager: [04] Apply Xref logic

activate Display
Display --> Display: clinician needs lab results
Display -> Manager: [05] PIXm Query [ITI-83]
Display <- Manager: PIXm Query results
Display --> Lab: [06] MHD request for lab result document
activate Lab

Lab --> Lab: find lab documents
Lab --> Display: return lab documents found

deactivate Display
deactivate Lab

@enduml