@startuml
hide footbox

participant "PIXm Manager" as Manager
box Main Hospital domain
 participant "Hospital Registration \n PIXm Source" as Source2
endbox

activate Source2
Source2 --> Source2: update patient demographics
Source2 -> Manager: [07] PIXm Feed (Update) [ITI-104]
activate Manager
deactivate Source2

Manager --> Manager: update identity information
Manager --> Manager: [08] Apply Xref logic

@enduml
