@startuml
hide footbox

participant "PIXm Manager" as Manager
box Main Hospital domain
 participant "Hospital Registration \n PIXm Source" as Source2
endbox

activate Source2

Note right of Source2
The registration system determined 
that two patient identifiers 
are the same patient person.
The local system (data) are 
merged/linked. 
endnote

Source2 -> Manager: [09] PIXm Feed (Resolve Duplicate) [ITI-104]
activate Manager
deactivate Source2

Manager --> Manager: [10] Apply Xref logic
@enduml